import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Theme } from "@radix-ui/themes";
import "@/app/globals.css";
import "@radix-ui/themes/styles.css";
import MobileToolBar from "../components/MobileToolBar/MobileToolBar";
import DesktopToolBar from "../components/DesktopToolBar/DesktopToolBar";
//font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Theme>
          <div className="flex min-h-screen">
            <DesktopToolBar />
            <div className="flex p-4 pt-6 justify-around w-full md:justify-center">
              <div>{children}</div>
            </div>
          </div>
          <MobileToolBar />
        </Theme>
      </body>
    </html>
  );
}
